version: "3"

services:

  sso_postgres:
    container_name: sso_postgres
    image: postgres:16.4
    environment:
      POSTGRES_USER: ${SSO_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SSO_POSTGRES_PASSWORD}
      POSTGRES_DB: ${SSO_POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - postgres-data-sso:/var/lib/postgresql/data
    ports:
      - "0.0.0.0:5555:5432"
    restart: unless-stopped
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - app-network

  sso_redis:
    container_name: redis_cache
    image: redis:7.4
    environment:
      REDIS_ADDR: ${SSO_REDIS_ADDR}
      REDIS_PASS: ${SSO_REDIS_PASSWORD}
      REDIS_CACHE: ${SSO_REDIS_DATABASE}
    env_file:
      - .env
    volumes:
      - redis-data-sso:/data
    ports:
      - '0.0.0.0:6379:6379'
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli', '-a', '$${REDIS_PASS}', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network


volumes:
  postgres-data-sso:
  redis-data-sso:

networks:
  app-network:
    driver: bridge
