grpc:
  readTimeout: 10s
  writeTimeout: 10s
  maxHeaderBytes: 1
  host: 0.0.0.0
  port: 44050

http:
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s
  host: 0.0.0.0
  port: 8080

auth:
  accessTokenTTL: 15m
  refreshTokenTTL: 43200m
  privateKeyPath: private.pem

postgres:
  connectTimeout: 5s
  maxConns: 10
  minConns: 2
  maxConnLifeTime: 2h
  maxConnIdleTime: 15m
  sslMode: "disable"

redis:
  poolSize: 10
  minIdleConns: 2
  dialTimeout: 5s
  readTimeout: 3s
  writeTimeout: 3s
  connMaxLifetime: 2h
  connMaxIdletime: 15m
